<h3>1. Create a table with a large number of records. Use MySQL Database. One can setup MySQL on localhost. Write some basic queries using python. Suppose you want to process/fetch a large number of records using python while keeping your memory usage low. Think of approaches on how to accomplish this and implement it.<h3>

In [1]:
import mysql.connector

mydb = mysql.connector.connect(host="localhost", user="root", passwd="Ruchit#170500", database="sakila")

mycursor = mydb.cursor()

mycursor.execute("show tables")

result = mycursor.fetchall()

for i in result:
	print(i)

('actor',)
('actor_info',)
('address',)
('category',)
('city',)
('country',)
('customer',)
('customer_list',)
('film',)
('film_actor',)
('film_category',)
('film_list',)
('film_text',)
('inventory',)
('language',)
('nicer_but_slower_film_list',)
('payment',)
('rental',)
('sales_by_film_category',)
('sales_by_store',)
('staff',)
('staff_list',)
('store',)

In [2]:
def generator(query):
    mycursor.execute(query)
    result = mycursor.fetchall()
    for row in result:
        yield(row)

In [3]:
countries = generator("select * from country")
for rows in countries:
    print(rows)
    print("\n")

(1, 'Afghanistan', datetime.datetime(2006, 2, 15, 4, 44))


(2, 'Algeria', datetime.datetime(2006, 2, 15, 4, 44))


(3, 'American Samoa', datetime.datetime(2006, 2, 15, 4, 44))


(4, 'Angola', datetime.datetime(2006, 2, 15, 4, 44))


(5, 'Anguilla', datetime.datetime(2006, 2, 15, 4, 44))


(6, 'Argentina', datetime.datetime(2006, 2, 15, 4, 44))


(7, 'Armenia', datetime.datetime(2006, 2, 15, 4, 44))


(8, 'Australia', datetime.datetime(2006, 2, 15, 4, 44))


(9, 'Austria', datetime.datetime(2006, 2, 15, 4, 44))


(10, 'Azerbaijan', datetime.datetime(2006, 2, 15, 4, 44))


(11, 'Bahrain', datetime.datetime(2006, 2, 15, 4, 44))


(12, 'Bangladesh', datetime.datetime(2006, 2, 15, 4, 44))


(13, 'Belarus', datetime.datetime(2006, 2, 15, 4, 44))


(14, 'Bolivia', datetime.datetime(2006, 2, 15, 4, 44))


(15, 'Brazil', datetime.datetime(2006, 2, 15, 4, 44))


(16, 'Brunei', datetime.datetime(2006, 2, 15, 4, 44))


(17, 'Bulgaria', datetime.datetime(2006, 2, 15, 4, 44))


(18, 'Cambodia', datetime.datetime(2006, 2, 15, 4, 44))


(19, 'Cameroon', datetime.datetime(2006, 2, 15, 4, 44))


(20, 'Canada', datetime.datetime(2006, 2, 15, 4, 44))


(21, 'Chad', datetime.datetime(2006, 2, 15, 4, 44))


(22, 'Chile', datetime.datetime(2006, 2, 15, 4, 44))


(23, 'China', datetime.datetime(2006, 2, 15, 4, 44))


(24, 'Colombia', datetime.datetime(2006, 2, 15, 4, 44))


(25, 'Congo, The Democratic Republic of the', datetime.datetime(2006, 2, 15, 4, 44))


(26, 'Czech Republic', datetime.datetime(2006, 2, 15, 4, 44))


(27, 'Dominican Republic', datetime.datetime(2006, 2, 15, 4, 44))


(28, 'Ecuador', datetime.datetime(2006, 2, 15, 4, 44))


(29, 'Egypt', datetime.datetime(2006, 2, 15, 4, 44))


(30, 'Estonia', datetime.datetime(2006, 2, 15, 4, 44))


(31, 'Ethiopia', datetime.datetime(2006, 2, 15, 4, 44))


(32, 'Faroe Islands', datetime.datetime(2006, 2, 15, 4, 44))


(33, 'Finland', datetime.datetime(2006, 2, 15, 4, 44))


(34, 'France', datetime.datetime(2006, 2, 15, 4, 44))


(35, 'French Guiana', datetime.datetime(2006, 2, 15, 4, 44))


(36, 'French Polynesia', datetime.datetime(2006, 2, 15, 4, 44))


(37, 'Gambia', datetime.datetime(2006, 2, 15, 4, 44))


(38, 'Germany', datetime.datetime(2006, 2, 15, 4, 44))


(39, 'Greece', datetime.datetime(2006, 2, 15, 4, 44))


(40, 'Greenland', datetime.datetime(2006, 2, 15, 4, 44))


(41, 'Holy See (Vatican City State)', datetime.datetime(2006, 2, 15, 4, 44))


(42, 'Hong Kong', datetime.datetime(2006, 2, 15, 4, 44))


(43, 'Hungary', datetime.datetime(2006, 2, 15, 4, 44))


(44, 'India', datetime.datetime(2006, 2, 15, 4, 44))


(45, 'Indonesia', datetime.datetime(2006, 2, 15, 4, 44))


(46, 'Iran', datetime.datetime(2006, 2, 15, 4, 44))


(47, 'Iraq', datetime.datetime(2006, 2, 15, 4, 44))


(48, 'Israel', datetime.datetime(2006, 2, 15, 4, 44))


(49, 'Italy', datetime.datetime(2006, 2, 15, 4, 44))


(50, 'Japan', datetime.datetime(2006, 2, 15, 4, 44))


(51, 'Kazakstan', datetime.datetime(2006, 2, 15, 4, 44))


(52, 'Kenya', datetime.datetime(2006, 2, 15, 4, 44))


(53, 'Kuwait', datetime.datetime(2006, 2, 15, 4, 44))


(54, 'Latvia', datetime.datetime(2006, 2, 15, 4, 44))


(55, 'Liechtenstein', datetime.datetime(2006, 2, 15, 4, 44))


(56, 'Lithuania', datetime.datetime(2006, 2, 15, 4, 44))


(57, 'Madagascar', datetime.datetime(2006, 2, 15, 4, 44))


(58, 'Malawi', datetime.datetime(2006, 2, 15, 4, 44))


(59, 'Malaysia', datetime.datetime(2006, 2, 15, 4, 44))


(60, 'Mexico', datetime.datetime(2006, 2, 15, 4, 44))


(61, 'Moldova', datetime.datetime(2006, 2, 15, 4, 44))


(62, 'Morocco', datetime.datetime(2006, 2, 15, 4, 44))


(63, 'Mozambique', datetime.datetime(2006, 2, 15, 4, 44))


(64, 'Myanmar', datetime.datetime(2006, 2, 15, 4, 44))


(65, 'Nauru', datetime.datetime(2006, 2, 15, 4, 44))


(66, 'Nepal', datetime.datetime(2006, 2, 15, 4, 44))


(67, 'Netherlands', datetime.datetime(2006, 2, 15, 4, 44))


(68, 'New Zealand', datetime.datetime(2006, 2, 15, 4, 44))


(69, 'Nigeria', datetime.datetime(2006, 2, 15, 4, 44))


(70, 'North Korea', datetime.datetime(2006, 2, 15, 4, 44))


(71, 'Oman', datetime.datetime(2006, 2, 15, 4, 44))


(72, 'Pakistan', datetime.datetime(2006, 2, 15, 4, 44))


(73, 'Paraguay', datetime.datetime(2006, 2, 15, 4, 44))


(74, 'Peru', datetime.datetime(2006, 2, 15, 4, 44))


(75, 'Philippines', datetime.datetime(2006, 2, 15, 4, 44))


(76, 'Poland', datetime.datetime(2006, 2, 15, 4, 44))


(77, 'Puerto Rico', datetime.datetime(2006, 2, 15, 4, 44))


(78, 'Romania', datetime.datetime(2006, 2, 15, 4, 44))


(79, 'Runion', datetime.datetime(2006, 2, 15, 4, 44))


(80, 'Russian Federation', datetime.datetime(2006, 2, 15, 4, 44))


(81, 'Saint Vincent and the Grenadines', datetime.datetime(2006, 2, 15, 4, 44))


(82, 'Saudi Arabia', datetime.datetime(2006, 2, 15, 4, 44))


(83, 'Senegal', datetime.datetime(2006, 2, 15, 4, 44))


(84, 'Slovakia', datetime.datetime(2006, 2, 15, 4, 44))


(85, 'South Africa', datetime.datetime(2006, 2, 15, 4, 44))


(86, 'South Korea', datetime.datetime(2006, 2, 15, 4, 44))


(87, 'Spain', datetime.datetime(2006, 2, 15, 4, 44))


(88, 'Sri Lanka', datetime.datetime(2006, 2, 15, 4, 44))


(89, 'Sudan', datetime.datetime(2006, 2, 15, 4, 44))


(90, 'Sweden', datetime.datetime(2006, 2, 15, 4, 44))


(91, 'Switzerland', datetime.datetime(2006, 2, 15, 4, 44))


(92, 'Taiwan', datetime.datetime(2006, 2, 15, 4, 44))


(93, 'Tanzania', datetime.datetime(2006, 2, 15, 4, 44))


(94, 'Thailand', datetime.datetime(2006, 2, 15, 4, 44))


(95, 'Tonga', datetime.datetime(2006, 2, 15, 4, 44))


(96, 'Tunisia', datetime.datetime(2006, 2, 15, 4, 44))


(97, 'Turkey', datetime.datetime(2006, 2, 15, 4, 44))


(98, 'Turkmenistan', datetime.datetime(2006, 2, 15, 4, 44))


(99, 'Tuvalu', datetime.datetime(2006, 2, 15, 4, 44))


(100, 'Ukraine', datetime.datetime(2006, 2, 15, 4, 44))


(101, 'United Arab Emirates', datetime.datetime(2006, 2, 15, 4, 44))


(102, 'United Kingdom', datetime.datetime(2006, 2, 15, 4, 44))


(103, 'United States', datetime.datetime(2006, 2, 15, 4, 44))


(104, 'Venezuela', datetime.datetime(2006, 2, 15, 4, 44))


(105, 'Vietnam', datetime.datetime(2006, 2, 15, 4, 44))


(106, 'Virgin Islands, U.S.', datetime.datetime(2006, 2, 15, 4, 44))


(107, 'Yemen', datetime.datetime(2006, 2, 15, 4, 44))


(108, 'Yugoslavia', datetime.datetime(2006, 2, 15, 4, 44))


(109, 'Zambia', datetime.datetime(2006, 2, 15, 4, 44))

<h3>2. Define a class Person and its two child classes: Male and Female. All classes have a method "get_gender" which can print "Male" for Male class and "Female" for Female Class. 
Bonus: Make class Person an abstract class and make get_gender an abstract method in the same class. The two child classes must inherit and implement get_gender. i.e., When trying to initialize an object of class Person, the program must throw an error.<h3>

In [4]:
from abc import ABC,abstractmethod

class Person(ABC):
  @abstractmethod
  def get_gender(self):
    pass


class Male(Person):
  def get_gender(self):
    print("Male")

class Female(Person):
  def get_gender(self):
    print("Female")

In [5]:
result = Male()
result.get_gender()

Male

In [6]:
result = Female()
result.get_gender()

Female

<h3>3. With a given list [12,24,35,24,88,120,155,88,120,155], write a program to print this list after removing all duplicate values with original order reserved. <h3>

In [7]:
def removeDuplicates(lst):
    newList = set()
    l2=[]
    for i in lst:
        if i not in newList:
            newList.add(i)
            l2.append(i)
    return l2

In [8]:
list_of_numbers = [12,24,35,24,88,155,120,88,120,155]
print(removeDuplicates(list_of_numbers))

[12, 24, 35, 88, 155, 120]

<h3>4. Write a program that can map() to make a list whose elements are squares of numbers between 1 and 20 (both included). <h3>

In [9]:
print(list(map(lambda x : x*x, [x for x in range(1,21)])))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]

<h3>5. Write a program anti_html.py that takes a URL as an argument, downloads the HTML from the web, and prints it after stripping HTML tags.<h3>

In [10]:
from bs4 import BeautifulSoup
import urllib

url ="https://www.google.com"

def antiHTML(url):
    response = urllib.request.urlopen(url).read()
    soup = BeautifulSoup(response, 'html.parser')
    strips = list(soup.stripped_strings)
    return strips

print(antiHTML(url))

['Google', 'Search', 'Images', 'Maps', 'Play', 'YouTube', 'News', 'Gmail', 'Drive', 'More', '»', 'Web History', '|', 'Settings', '|', 'Sign in', 'Advanced search', 'Google offered in:', 'हिन्दी', 'বাংলা', 'తెలుగు', 'मराठी', 'தமிழ்', 'ગુજરાતી', 'ಕನ್ನಡ', 'മലയാളം', 'ਪੰਜਾਬੀ', 'Advertising\xa0Programs', 'Business Solutions', 'About Google', 'Google.co.in', '© 2022 -', 'Privacy', '-', 'Terms']